name: matrix-demo

on:
  workflow_dispatch:

jobs:
  code-format:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go : ['1.22','1.23','1.24']
    steps:
      - name : setup go
        uses: actions/setup-go@v6
        with:
            go-version: ${{ matrix.go}}
            go-version-file: 'go.mod' 
            cache-dependency-path: 'go.sum'

      - name: Run go formatter
        run: go fmt
        working-directory: backend

      - name: Run go vet
        run: go vet
        working-directory: backend
        
            
